# steps:
#     # build the container image
#     - name: 'gcr.io/cloud-builders/docker'
#       args: [ 'build', '-t', 'gcr.io/insider-hoods321/clientt', '.' ]
#     # push the container image to gcr
#     - name: 'gcr.io/cloud-builders/docker'
#       args: [ 'push', 'gcr.io/insider-hoods321/clientt']
#       # Deploy container image to Cloud Run
#     - name: "gcr.io/cloud-builders/gcloud"
#       args: ['run', 'deploy', 'clientt', '--image', 'gcr.io/insider-hoods321/clientt', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']


steps:
  # Build and push the backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/insider-hoods321/backend', './backend']
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']
    id: 'push-backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'backend-service', '--image', 'gcr.io/$PROJECT_ID/backend', '--region', 'us-central1']
    id: 'deploy-backend'

  # Build and push the client service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/insider-hoods321/client', './client']
    id: 'build-client'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/client']
    id: 'push-client'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'client-service', '--image', 'gcr.io/$PROJECT_ID/client', '--region', 'us-central1']
    id: 'deploy-client'

      