steps:
  # Build and push the backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/insider-hoods321/backend', './backend']
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/insider-hoods321/backend']
    id: 'push-backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'backendd', '--image', 'gcr.io/insider-hoods321/backend', '--region', 'us-central1']
    id: 'deploy-backend'

  # Build and push the client service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/insider-hoods321/client', './client']
    id: 'build-client'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/insider-hoods321/client']
    id: 'push-client'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'clientt', '--image', 'gcr.io/insider-hoods321/client', '--region', 'us-central1']
    id: 'deploy-client'

  # Build and push the Python backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/insider-hoods321/open-data-backend', './open-data-backend']
    id: 'build-open-data-backendd'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/insider-hoods321/open-data-backend']
    id: 'push-open-data-backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'open-data-backend', '--image', 'gcr.io/insider-hoods321/open-data-backend', '--region', 'us-central1']
    id: 'deploy-python-backend'