const e= {
  id: 'cs_test_a1pSTXmyBxtc0oiEWXSnK2wUrql6qhzeb4iPMHro6xvsXrlY1DRgarBVby',
  object: 'checkout.session',
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 100,
  amount_total: 100,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: null,
  cancel_url: 'http://localhost:3000/canceled',
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: null,
  created: 1711891440,
  currency: 'usd',
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null
  },
  customer: null,
  customer_creation: 'if_required',
  customer_details: {
    address: {
      city: 'Jersey City',
      country: 'US',
      line1: '15 Carbon Place',
      line2: null,
      postal_code: '07305',
      state: 'NJ'
    },
    email: 'asdf@gmail.com',
    name: 'Diego Robayo',
    phone: null,
    tax_exempt: 'none',
    tax_ids: []
  },
  customer_email: 'asdf@gmail.com',
  expires_at: 1711977840,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: null,
      metadata: {},
      rendering_options: null
    }
  },
  livemode: false,
  locale: null,
  metadata: {},
  mode: 'payment',
  payment_intent: 'pi_3P0ONDCjli54jhBv1hWNrdMT',
  payment_link: null,
  payment_method_collection: 'if_required',
  payment_method_configuration_details: null,
  payment_method_options: { card: { request_three_d_secure: 'automatic' } },
  payment_method_types: ['card'],
  payment_status: 'paid',
  phone_number_collection: { enabled: false },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: { allowed_countries: ['GB', 'US'] },
  shipping_cost: null,
  shipping_details: {
    address: {
      city: 'Jersey City',
      country: 'US',
      line1: '15 Carbon Place',
      line2: null,
      postal_code: '07305',
      state: 'NJ'
    },
    name: 'Diego Robayo'
  },
  shipping_options: [],
  status: 'complete',
  submit_type: null,
  subscription: null,
  success_url: 'http://localhost:3000/success?session_id={CHECKOUT_SESSION_ID}',
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: 'hosted',
  url: null
}